AWSTemplateFormatVersion: "2010-09-09"
Description: Practice 1
Transform:
  - AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 30
    MemorySize: 1024
    Environment:
      Variables:
        USERNAME: Jordi
        NODE_OPTIONS: --enable-source-maps
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

Resources:
  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-hello-world-lambda'
      Handler: helloWorld.handler
      CodeUri: dist/practice1
      Role: !GetAtt LambdaExecutionRole.Arn


  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-BasicLambdaExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                lambda.amazonaws.com
            Action:
              sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  Dynamodb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-dynamodb-table'
      AttributeDefinitions:
        - AttributeName: id  # Partition key
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ################################################### PRACTICE 2 ###################################################
  ### ROLE write definition
  LambdaWriteDynamodbRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-LambdaWriteDynamodbRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                lambda.amazonaws.com
            Action:
              sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-LambdaWriteDynamodbPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource:
                  - !GetAtt Dynamodb.Arn


  ## Lambda write definition
  PutLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-put-dynamodb-lambda'
      Handler: put.handler
      CodeUri: dist/practice2
      Role: !GetAtt LambdaWriteDynamodbRole.Arn


  ### ROLE read definition
  LambdaReadDynamodbRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-LambdaReadDynamodbRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                lambda.amazonaws.com
            Action:
              sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-LambdaReadDynamodbPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource:
                  - !GetAtt Dynamodb.Arn

  ## Lambda read definition
  GetLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-get-dynamodb-lambda'
      Handler: get.handler
      CodeUri: dist/practice2
      Role: !GetAtt LambdaReadDynamodbRole.Arn


  ### ROLE read definition
  LambdaDeleteDynamodbRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-LambdaDeleteDynamodbRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                lambda.amazonaws.com
            Action:
              sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-LambdaDeleteDynamodbPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DeleteItem
                Resource:
                  - !GetAtt Dynamodb.Arn

  ## Lambda read definition
  DeleteLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-delete-dynamodb-lambda'
      Handler: delete.handler
      CodeUri: dist/practice2
      Role: !GetAtt LambdaDeleteDynamodbRole.Arn
      # Option bellow is a valid option as well,
      # and I won't have to declare the role for it.
      # The role line above should have to be deleted to make policies have effect.
#      Policies:
#        - Statement:
#            - Effect: Allow
#              Action:
#                - dynamodb:DeleteItem
#              Resource:
#                - !GetAtt Dynamodb.Arn

  ################################################### PRACTICE 3 #####
  ##############################################
  # Event bridge definition
  EventBridge:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub '${AWS::StackName}-event-bridge'

  # Event bridge rules definition
  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !GetAtt EventBridge.Arn
      EventPattern:
        source:
          - "player2"
      Name: !Sub '${AWS::StackName}-events-from-player-one-rule'
      State: ENABLED
      Targets:
        -
          Arn: !GetAtt HelloWorldLambda.Arn
          Id: "HelloWorldLambda"

  # Give event permission to invoke lambda
  EventBridgeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: "HelloWorldLambda"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt EventBridgeRule.Arn